//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopKey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TopKey.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;KeyboardProfile xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;_DEFAULT&lt;/Name&gt;
        ///  &lt;SelectedKeys&gt;
        ///    &lt;Keys&gt;Right&lt;/Keys&gt;
        ///    &lt;Keys&gt;Left&lt;/Keys&gt;
        ///    &lt;Keys&gt;Down&lt;/Keys&gt;
        ///    &lt;Keys&gt;Up&lt;/Keys&gt;
        ///    &lt;Keys&gt;RightShift&lt;/Keys&gt;
        ///    &lt;Keys&gt;LeftShift&lt;/Keys&gt;
        ///    &lt;Keys&gt;Tab&lt;/Keys&gt;
        ///    &lt;Keys&gt;OEMPlus&lt;/Keys&gt;
        ///    &lt;Keys&gt;N8&lt;/Keys&gt;
        ///    &lt;Keys&gt;N9&lt;/Keys&gt;
        ///    &lt;Keys&gt;N0&lt;/Keys&gt;
        ///    &lt;Keys&gt;OEMMinus&lt;/Keys&gt;
        ///    &lt;Keys&gt;N4&lt;/Keys&gt;
        ///    &lt;Keys&gt;N5&lt;/Keys&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _DEFAULT {
            get {
                return ResourceManager.GetString("_DEFAULT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Crispy_Computer_Mouse_Top_Down_View_clip_art_medium {
            get {
                object obj = ResourceManager.GetObject("Crispy_Computer_Mouse_Top_Down_View_clip_art_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
